apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: my-redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       app: my-redis
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPollicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
